baseURL = "https://horriblebosses.netlify.com"
languageCode = "en-us"
title = "IT Leadership - TAG NW"
theme = "infinity-hugo"

[params]

    # Navigation
    [params.navigation]
        logo = "images/tag-logo.png"
        home = "Home"
        about = "About"
        #service = "Services"
        contact = "Contact"

    # Hero Area
    [params.hero]
        enable      = true
        bg          = "images/header-bg.jpg"
        title       = "HUNGRY?"
        subtitle    = "Join us at the next IT Leadership lunch, every second Wednesday. \n\n Grab a recurring calendar reminder!"
        btnText     = "Get Started"
        countdownYear = "2020"
        countdownMonth = "02"
        countdownDay  = "12"

    # About Section
    [params.about]
        enable      = true
        heading     = "Join IT leaders to share questions, solutions, ideas and more in a casual lunch environment."
        description = "The IT Leadership group was founded to better connect the IT community in Whatcom and Skagit counties. We welcome both current and aspirational IT leaders to gather informally and connect. \n\n We meet monthly in Bellingham, WA, at [Brandywine Kitchen](http://www.brandywinekitchen.com) in the upstairs mezzanine."

        [[params.about.sliderItem]]
            image   = "images/about/map.png"
        #[[params.about.sliderItem]]
            #image   = "images/about/2.jpg"
        
    # Call to Action Section
    [params.cta]
        enable      = false
        bg          = "images/call-to-action.jpg"
        title       = "Subscribe to our mailing list"
        subtitle    = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"

    [params.contact]
        enable      = true
        title       = "RSVP"
        subtitle    = "To RSVP for lunch, or if you have any questions before attending, get in touch!"
